### ISSUE TITLE
escrowAccountSetsMultisig lowThreshold should be 1 or 2

### ISSUE THREAD

**Issue by mcchin** [slyg/stellar-tinkering#1]
https://github.com/slyg/stellar-tinkering/blob/master/escrow-funding-and-release/scripts/4_escrowAccountSetsMultisig

```
const thresholds = {
    masterWeight: 0, // Escrow account has a weight of 0, no rights :)
    lowThreshold: 1,
    medThreshold: 2, // payment is medium threshold
    highThreshold: 2,
}
```

Wondering if lowThreshold should be 1 or 2?

**Comment by slyg** [comment]
Oops right, in this case I'd rather have chosen `2` you are right thank you !
